/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.PilaC;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author HiYeaismin 8a
 */
public class Pilas extends javax.swing.JFrame {

    /**
     * Creates new form Pilas
     */
    public Pilas() {
        initComponents();
        lblQuedan.setVisible(false);
        btnBorrar.setVisible(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIngresar = new javax.swing.JTextField();
        lblIngresar = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        lblQuedan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIngresarKeyPressed(evt);
            }
        });

        lblIngresar.setText("Tamaño:");

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        lblQuedan.setText("Te quedan:  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(txtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblQuedan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblQuedan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void merequetengueKey(KeyEvent evt){
if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (lblIngresar.getText() == "Tamaño:") {
                
                pila.setTamaño(Integer.parseInt(txtIngresar.getText()));
                JOptionPane.showMessageDialog(this, "El tamaño de la pila será de:" + pila.getTamaño());
                pila.inicializararreglo();
                txtIngresar.setText("");
                lblIngresar.setText("Ingresar: ");
                
            } else {
                btnBorrar.setVisible(true);
                //for (int iteracion = 0; iteracion <= pila.getTamaño(); iteracion++) {
                    try {
                        int valorIngresar = Integer.parseInt(txtIngresar.getText());
                        boolean a = pila.ingresar(valorIngresar);
                        txtIngresar.setText("");
                        if (a == true) {
                            lblQuedan.setVisible(true);
                            lblQuedan.setText((pila.tamaño - 1 - pila.tos) + " Espacios disponibles.");
                        }else{
                            txtIngresar.setEnabled(false);
                            lblQuedan.setText("Ya NO hay espacios D.");
                        }
                    } catch (NumberFormatException error) {
                        JOptionPane.showMessageDialog(this, "Ingrese números.");
                    }
                //}
            }
        }
}
    private void txtIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarKeyPressed
        // TODO add your handling code here:
        merequetengueKey(evt);
        
    }//GEN-LAST:event_txtIngresarKeyPressed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if(pila.eliminar()== true){
            JOptionPane.showMessageDialog(this, "El " + pila.valorEliminado + " Se dascartará de la pila.");
        }
        else{
            JOptionPane.showMessageDialog(this, "Nimodo, no tienes más elementos que quitar.");
            txtIngresar.setEnabled(true);
            lblIngresar.setText("Tamaño:");
            lblQuedan.setText("");
            
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pilas().setVisible(true);
            }
        });
    }
    PilaC pila = new PilaC();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblQuedan;
    private javax.swing.JTextField txtIngresar;
    // End of variables declaration//GEN-END:variables
}
